services:
  angulargabs:
    restart: unless-stopped
    image: angulargabs:latest
    container_name: angulargabs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:4200"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    